/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    systems: System;
    capabilities: Capability;
    'process-stages': ProcessStage;
    'proof-points': ProofPoint;
    'case-studies': CaseStudy;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    systems: SystemsSelect<false> | SystemsSelect<true>;
    capabilities: CapabilitiesSelect<false> | CapabilitiesSelect<true>;
    'process-stages': ProcessStagesSelect<false> | ProcessStagesSelect<true>;
    'proof-points': ProofPointsSelect<false> | ProofPointsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    identity: Identity;
    now: Now;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    identity: IdentitySelect<false> | IdentitySelect<true>;
    now: NowSelect<false> | NowSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage users and settings. Editors manage content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers. Required for every upload.
   */
  alt: string;
  /**
   * Optional caption shown beneath the image in editorial contexts.
   */
  caption?: string | null;
  category?: ('system' | 'portrait' | 'artifact' | 'other') | null;
  /**
   * Optional absolute path already served by the site (for example /demo-assets/systems/nepal-ipms-hero.webp). When set, the export uses this instead of an uploaded file.
   */
  staticPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Products and platforms shown in chapter 02 of the Product Lab. Order controls the switcher sequence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "systems".
 */
export interface System {
  id: number;
  name: string;
  /**
   * Stable identifier used by the frontend switcher.
   */
  slug: string;
  status: 'LIVE' | 'SCALING' | 'BUILDING' | 'EXPERIMENT' | 'ARCHIVED';
  /**
   * For example: LegalTech SaaS
   */
  category: string;
  /**
   * Short stack line, e.g. Cloudflare · Next.js
   */
  tech: string;
  /**
   * One sentence describing what the system is for.
   */
  purpose: string;
  /**
   * The four beats rendered in the system detail panel.
   */
  story: {
    problem: string;
    system: string;
    intelligence: string;
    outcome: string;
  };
  /**
   * Rendered as a middot-separated stack line.
   */
  build?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Product preview image. Falls back to the media record staticPath when unset.
   */
  preview?: (number | null) | Media;
  /**
   * External URL or internal path.
   */
  link: string;
  linkLabel: string;
  /**
   * Optional long-form case study for this system.
   */
  caseStudy?: (number | null) | CaseStudy;
  /**
   * Capabilities this system demonstrates.
   */
  capabilities?: (number | Capability)[] | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Selected by default when the Product Lab loads.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Long-form writeups behind each system. These map to the /case/* pages on the main site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  /**
   * e.g. Case study · Education platform
   */
  kicker: string;
  /**
   * The one-line outcome shown under the title.
   */
  impact: string;
  /**
   * Product / Problem / My role / Outcome definition list.
   */
  brief?:
    | {
        term: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main narrative. Supports headings, lists, links, and media.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Production URL, if the system is public.
   */
  liveUrl?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Chapter 04 — what Prakash can be hired to build.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities".
 */
export interface Capability {
  id: number;
  title: string;
  slug: string;
  /**
   * Two lines maximum — this renders inside a compact grid cell.
   */
  detail: string;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  order: number;
  /**
   * Span two columns in the capability grid.
   */
  wide?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Chapter 03 — the build method accordion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-stages".
 */
export interface ProcessStage {
  id: number;
  /**
   * Rendered uppercase, e.g. ARCHITECTURE
   */
  title: string;
  /**
   * Also drives the displayed 01–06 index.
   */
  order: number;
  body: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Verified production numbers shown in the hero. No vanity metrics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-points".
 */
export interface ProofPoint {
  id: number;
  /**
   * e.g. 130K+
   */
  value: string;
  /**
   * e.g. Trademark records handled
   */
  label: string;
  order: number;
  /**
   * Where this number comes from. Internal only — keeps claims auditable.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'systems';
        value: number | System;
      } | null)
    | ({
        relationTo: 'capabilities';
        value: number | Capability;
      } | null)
    | ({
        relationTo: 'process-stages';
        value: number | ProcessStage;
      } | null)
    | ({
        relationTo: 'proof-points';
        value: number | ProofPoint;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  staticPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "systems_select".
 */
export interface SystemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  category?: T;
  tech?: T;
  purpose?: T;
  story?:
    | T
    | {
        problem?: T;
        system?: T;
        intelligence?: T;
        outcome?: T;
      };
  build?:
    | T
    | {
        value?: T;
        id?: T;
      };
  preview?: T;
  link?: T;
  linkLabel?: T;
  caseStudy?: T;
  capabilities?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities_select".
 */
export interface CapabilitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  detail?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  order?: T;
  wide?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-stages_select".
 */
export interface ProcessStagesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-points_select".
 */
export interface ProofPointsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  order?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kicker?: T;
  impact?: T;
  brief?:
    | T
    | {
        term?: T;
        description?: T;
        id?: T;
      };
  body?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  liveUrl?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Chapter 01 — who this is, and the language used across the lab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  name: string;
  role: string;
  location: string;
  /**
   * e.g. PKA-2026
   */
  builderId: string;
  /**
   * e.g. v2.1
   */
  version: string;
  /**
   * Hero portrait shown in the identity card.
   */
  portrait?: (number | null) | Media;
  /**
   * First headline line (solid).
   */
  headlineLead: string;
  /**
   * Second headline line (outlined).
   */
  headlineOutline: string;
  positioning: string;
  /**
   * Quoted at the top of the process chapter.
   */
  philosophy: string;
  disciplines?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  email: string;
  fullSite: string;
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chapter 05 — what is on the bench and what work is open.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "now".
 */
export interface Now {
  id: number;
  /**
   * e.g. AVAILABLE FOR SELECTED WORK
   */
  status: string;
  building: {
    title: string;
    note: string;
  };
  focus?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  available?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Navigation, chapter sequence, and shared SEO defaults for the Product Lab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Drives the navbar, the chapter rail, and the numbered cues in each section.
   */
  chapters?:
    | {
        /**
         * e.g. 01
         */
        index: string;
        id: string | null;
        label: string;
      }[]
    | null;
  siteTitle: string;
  siteDescription: string;
  ogImage?: (number | null) | Media;
  /**
   * Browser theme colour for the Product Lab.
   */
  themeColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  name?: T;
  role?: T;
  location?: T;
  builderId?: T;
  version?: T;
  portrait?: T;
  headlineLead?: T;
  headlineOutline?: T;
  positioning?: T;
  philosophy?: T;
  disciplines?:
    | T
    | {
        value?: T;
        id?: T;
      };
  email?: T;
  fullSite?: T;
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "now_select".
 */
export interface NowSelect<T extends boolean = true> {
  status?: T;
  building?:
    | T
    | {
        title?: T;
        note?: T;
      };
  focus?:
    | T
    | {
        value?: T;
        id?: T;
      };
  available?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  chapters?:
    | T
    | {
        index?: T;
        id?: T;
        label?: T;
      };
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  themeColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}